export const data = [
  {
    id: 1,
    sn: 1,
    facility: "Facility A",
    amount: 1000,
    date: "01/01/21",
    points: "5 points",
    action: "5 points",
  },
  {
    id: 2,
    sn: 2,
    facility: "Facility B",
    amount: 1500,
    date: "02/01/21",
    points: "10 points",
    action: "10 points",
  },
  {
    id: 3,
    sn: 3,
    facility: "Facility C",
    amount: 1200,
    date: "03/01/21",
    points: "5 points",
    action: "5 points",
  },
  {
    id: 4,
    sn: 4,
    facility: "Facility D",
    amount: 1800,
    date: "04/01/21",
    points: "5 points",
    action: "5 points",
  },
  {
    id: 5,
    sn: 5,
    facility: "Facility E",
    amount: 1300,
    date: "05/01/21",
    points: "5 points",
    action: "5 points",
  },
  {
    id: 6,
    sn: 6,
    facility: "Facility F",
    amount: 1600,
    date: "06/01/21",
    points: "5 points",
    action: "5 points",
  },
];
